kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: aliyun
  namespace: default
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aliyun
              image: 'aliyun:security_group'
              env:
                - name: access_key
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: access_key
                - name: access_secret
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: access_secret
                - name: port_list
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: port_list
                - name: redis_host
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: redis_host
                - name: redis_password
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: redis_password
                - name: redis_port
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: redis_port
                - name: region_id
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: region_id
                - name: sg_id
                  valueFrom:
                    configMapKeyRef:
                      name: aliyun
                      key: sg_id
              imagePullPolicy: Always
          restartPolicy: Never
